name: Rust

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.1

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rust-src

      - name: Install rust-analyzer
        run: |
          curl -L https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > /usr/local/bin/rust-analyzer
          chmod +x /usr/local/bin/rust-analyzer

      - name: Install jdtls
        run: |
          jdtls_dir=$(mktemp -d --suffix "jdtls")
          curl https://download.eclipse.org/jdtls/milestones/1.9.0/jdt-language-server-1.9.0-202203031534.tar.gz | tar --directory=$jdtls_dir -xzvf -
          ln -s $jdtls_dir/bin/jdtls /usr/local/bin/jdtls
          chmod +x /usr/local/bin/jdtls

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose -- --nocapture

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Compile Linux
        id: compile-linux
        uses: rust-build/rust-build.action@v1.3.2
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none

      - name: Upload linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: Linux binary
          path: |
            ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-linux.outputs.BUILT_CHECKSUM }}

      - name: Compile for Mac
        id: compile-mac
        uses: rust-build/rust-build.action@v1.3.2
        with:
          RUSTTARGET: x86_64-apple-darwin
          UPLOAD_MODE: none

      - name: Upload mac artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mac binary
          path: |
            ${{ steps.compile-mac.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-mac.outputs.BUILT_CHECKSUM }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-linux.outputs.BUILT_CHECKSUM }}
            ${{ steps.compile-mac.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-mac.outputs.BUILT_CHECKSUM }}
